# Build Snap
name: Snap Build

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    paths:
      - ".github/workflows/snap-build.yml"
  
env:
  NODE_VERSION: '20'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    outputs:
      snap: ${{ steps.snapcraft.outputs.snap }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy Sources
        run: rsync -r ./ distribution/terminusdb_source/

      - name: Build
        uses: snapcore/action-build@v1
        id: snapcraft
        with:
          path: distribution

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: terminusdb-snap
          path: ${{ steps.snapcraft.outputs.snap }}
        
  test:
    name: Integration Tests
    needs: 
      - build
    runs-on: ubuntu-latest

    steps:   
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download
        uses: actions/download-artifact@v4
        with:
          name: terminusdb-snap
          path: download_snap/

      - name: Install Snap
        run: sudo snap install download_snap/*.snap --dangerous

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Verify Working Directory
        run: |
            echo "Working directory: $(pwd)"
            echo "Directory is writable: $(test -w . && echo 'yes' || echo 'no')"
            echo "User: $(whoami)"

      - name: Init TerminusDB
        run: |
            terminusdb store init --key root
  
      - name: Start TerminusDB
        run: |
            terminusdb serve &
            echo $! > terminusdb.pid
            sleep 5  # wait for server to start
  
      - name: Test
        run: |
          # Tests run from repository root (writable)
          # CLI tests will create ./storage/* directories here
          export TERMINUSDB_EXEC_PATH=/snap/bin/terminusdb
          export TERMINUSDB_BASE_URL='http://127.0.0.1:6363'
          cd tests && npm i && npm run test

      - name: Stop TerminusDB
        run: |
          kill $(cat terminusdb.pid)
      
      - name: Cleanup Test Storage
        if: always()
        run: |
          # Clean up any storage directories created by CLI tests
          rm -rf ./storage 2>/dev/null || true      
        
